using MacroMat.Common;
using MacroMat.SystemCalls.Windows;

namespace MacroMat.Input;

internal static class InputKeyTranslator
{
    public static Scancode CurrentPlatformScancode(InputKey key)
    {
        return new OsSelector<Scancode>()
            .OnWindows(() => ToWindowsScancode(key))
            .Execute();
    }
    
    public static VirtualKey CurrentPlatformVirtual(InputKey key)
    {
        return new OsSelector<VirtualKey>()
            .OnWindows(() =>
            {
                var windowsVirtualKey = ToWindowsVirtual(key);

                return VirtualKey.From((byte)windowsVirtualKey);
            })
            .Execute();
    }
    
    #region Windows
    
    public static Scancode ToWindowsScancode(InputKey key)
    {
        // https://docs.google.com/spreadsheets/d/1GSj0gKDxyWAecB3SIyEZ2ssPETZkkxn67gdIwL1zFUs/edit#gid=0
        
        return key switch
        {
            InputKey.F1 => Scancode.From((short)Win32.WindowsScanCode.F1),
            InputKey.F2 => Scancode.From((short)Win32.WindowsScanCode.F2),
            InputKey.F3 => Scancode.From((short)Win32.WindowsScanCode.F3),
            InputKey.F4 => Scancode.From((short)Win32.WindowsScanCode.F4),
            InputKey.F5 => Scancode.From((short)Win32.WindowsScanCode.F5),
            InputKey.F6 => Scancode.From((short)Win32.WindowsScanCode.F6),
            InputKey.F7 => Scancode.From((short)Win32.WindowsScanCode.F7),
            InputKey.F8 => Scancode.From((short)Win32.WindowsScanCode.F8),
            InputKey.F9 => Scancode.From((short)Win32.WindowsScanCode.F9),
            InputKey.F10 => Scancode.From((short)Win32.WindowsScanCode.F10),
            InputKey.F11 => Scancode.From((short)Win32.WindowsScanCode.F11),
            InputKey.F12 => Scancode.From((short)Win32.WindowsScanCode.F12),
            InputKey.F13 => Scancode.From((short)Win32.WindowsScanCode.F13),
            InputKey.F14 => Scancode.From((short)Win32.WindowsScanCode.F14),
            InputKey.F15 => Scancode.From((short)Win32.WindowsScanCode.F15),
            InputKey.F16 => Scancode.From((short)Win32.WindowsScanCode.F16),
            InputKey.F17 => Scancode.From((short)Win32.WindowsScanCode.F17),
            InputKey.F18 => Scancode.From((short)Win32.WindowsScanCode.F18),
            InputKey.F19 => Scancode.From((short)Win32.WindowsScanCode.F19),
            InputKey.F20 => Scancode.From((short)Win32.WindowsScanCode.F20),
            InputKey.F21 => Scancode.From((short)Win32.WindowsScanCode.F21),
            InputKey.F22 => Scancode.From((short)Win32.WindowsScanCode.F22),
            InputKey.F23 => Scancode.From((short)Win32.WindowsScanCode.F23),
            InputKey.F24 => Scancode.From((short)Win32.WindowsScanCode.F24),
            InputKey.VolumeMute => Scancode.From((short)Win32.WindowsScanCode.VOLUME_MUTE),
            InputKey.VolumeDown => Scancode.From((short)Win32.WindowsScanCode.VOLUME_DOWN),
            InputKey.VolumeUp => Scancode.From((short)Win32.WindowsScanCode.VOLUME_UP),
            InputKey.PlaybackPrevious => Scancode.From((short)Win32.WindowsScanCode.MEDIA_PREV_TRACK),
            InputKey.PlaybackPlayPause => Scancode.From((short)Win32.WindowsScanCode.MEDIA_PLAY_PAUSE),
            InputKey.PlaybackNext => Scancode.From((short)Win32.WindowsScanCode.MEDIA_NEXT_TRACK),
            InputKey.Backtick => Scancode.From(0xC0),
            InputKey.Tilde => Scancode.From(0xC0),
            InputKey.Zero => Scancode.From((short)Win32.WindowsScanCode.KEY_0),
            InputKey.One => Scancode.From((short)Win32.WindowsScanCode.KEY_1),
            InputKey.Two => Scancode.From((short)Win32.WindowsScanCode.KEY_2),
            InputKey.Three => Scancode.From((short)Win32.WindowsScanCode.KEY_3),
            InputKey.Four => Scancode.From((short)Win32.WindowsScanCode.KEY_4),
            InputKey.Five => Scancode.From((short)Win32.WindowsScanCode.KEY_5),
            InputKey.Six => Scancode.From((short)Win32.WindowsScanCode.KEY_6),
            InputKey.Seven => Scancode.From((short)Win32.WindowsScanCode.KEY_7),
            InputKey.Eight => Scancode.From((short)Win32.WindowsScanCode.KEY_8),
            InputKey.Nine => Scancode.From((short)Win32.WindowsScanCode.KEY_9),
            InputKey.ExclamationPoint => Scancode.From((short)Win32.WindowsScanCode.KEY_1),
            InputKey.At => Scancode.From((short)Win32.WindowsScanCode.KEY_2),
            InputKey.Hashtag => Scancode.From((short)Win32.WindowsScanCode.KEY_3),
            InputKey.Dollar => Scancode.From((short)Win32.WindowsScanCode.KEY_4),
            InputKey.Percent => Scancode.From((short)Win32.WindowsScanCode.KEY_5),
            InputKey.Caret => Scancode.From((short)Win32.WindowsScanCode.KEY_6),
            InputKey.Ampersand => Scancode.From((short)Win32.WindowsScanCode.KEY_7),
            InputKey.Star => Scancode.From((short)Win32.WindowsScanCode.KEY_8),
            InputKey.LeftParenthesis => Scancode.From((short)Win32.WindowsScanCode.KEY_9),
            InputKey.RightParenthesis => Scancode.From((short)Win32.WindowsScanCode.KEY_0),
            InputKey.Dash => Scancode.From(0xBD),
            InputKey.Underscore => Scancode.From(0xBD),
            InputKey.Equals => Scancode.From(0xBB),
            InputKey.Plus => Scancode.From(0xBB),
            InputKey.LeftBracket => Scancode.From(0xDB),
            InputKey.LeftCurlyBracket => Scancode.From(0xDB),
            InputKey.RightBracket => Scancode.From(0xDD),
            InputKey.RightCurlyBracket => Scancode.From(0xDD),
            InputKey.VerticalBar => Scancode.From(0xDC),
            InputKey.Backslash => Scancode.From(0xDC),
            InputKey.Semicolon => Scancode.From(0xBA),
            InputKey.Colon => Scancode.From(0xBA),
            InputKey.SingleQuote => Scancode.From(0xDE),
            InputKey.DoubleQuote => Scancode.From(0xDE),
            InputKey.Comma => Scancode.From(0xBC),
            InputKey.LessThan => Scancode.From(0xBC),
            InputKey.Period => Scancode.From(0xBE),
            InputKey.GreaterThan => Scancode.From(0xBE),
            InputKey.Slash => Scancode.From(0xBF),
            InputKey.QuestionMark => Scancode.From(0xBF),
            InputKey.A => Scancode.From((short)Win32.WindowsScanCode.KEY_A),
            InputKey.B => Scancode.From((short)Win32.WindowsScanCode.KEY_B),
            InputKey.C => Scancode.From((short)Win32.WindowsScanCode.KEY_C),
            InputKey.D => Scancode.From((short)Win32.WindowsScanCode.KEY_D),
            InputKey.E => Scancode.From((short)Win32.WindowsScanCode.KEY_E),
            InputKey.F => Scancode.From((short)Win32.WindowsScanCode.KEY_F),
            InputKey.G => Scancode.From((short)Win32.WindowsScanCode.KEY_G),
            InputKey.H => Scancode.From((short)Win32.WindowsScanCode.KEY_H),
            InputKey.I => Scancode.From((short)Win32.WindowsScanCode.KEY_I),
            InputKey.J => Scancode.From((short)Win32.WindowsScanCode.KEY_J),
            InputKey.K => Scancode.From((short)Win32.WindowsScanCode.KEY_K),
            InputKey.L => Scancode.From((short)Win32.WindowsScanCode.KEY_L),
            InputKey.M => Scancode.From((short)Win32.WindowsScanCode.KEY_M),
            InputKey.N => Scancode.From((short)Win32.WindowsScanCode.KEY_N),
            InputKey.O => Scancode.From((short)Win32.WindowsScanCode.KEY_O),
            InputKey.P => Scancode.From((short)Win32.WindowsScanCode.KEY_P),
            InputKey.Q => Scancode.From((short)Win32.WindowsScanCode.KEY_Q),
            InputKey.R => Scancode.From((short)Win32.WindowsScanCode.KEY_R),
            InputKey.S => Scancode.From((short)Win32.WindowsScanCode.KEY_S),
            InputKey.T => Scancode.From((short)Win32.WindowsScanCode.KEY_T),
            InputKey.U => Scancode.From((short)Win32.WindowsScanCode.KEY_U),
            InputKey.V => Scancode.From((short)Win32.WindowsScanCode.KEY_V),
            InputKey.W => Scancode.From((short)Win32.WindowsScanCode.KEY_W),
            InputKey.X => Scancode.From((short)Win32.WindowsScanCode.KEY_X),
            InputKey.Y => Scancode.From((short)Win32.WindowsScanCode.KEY_Y),
            InputKey.Z => Scancode.From((short)Win32.WindowsScanCode.KEY_Z),
            InputKey.Shift => Scancode.From((short)Win32.WindowsScanCode.SHIFT),
            InputKey.LeftShift => Scancode.From((short)Win32.WindowsScanCode.LSHIFT),
            InputKey.RightShift => Scancode.From((short)Win32.WindowsScanCode.RSHIFT),
            InputKey.Alt => Scancode.From(0x12),
            InputKey.LeftAlt => Scancode.From(0xA4),
            InputKey.RightAlt => Scancode.From(0xA5),
            InputKey.Control => Scancode.From((short)Win32.WindowsScanCode.CONTROL),
            InputKey.LeftControl => Scancode.From((short)Win32.WindowsScanCode.LCONTROL),
            InputKey.RightControl => Scancode.From((short)Win32.WindowsScanCode.RCONTROL),
            InputKey.Enter => Scancode.From((short)Win32.WindowsScanCode.RETURN),
            InputKey.Tab => Scancode.From((short)Win32.WindowsScanCode.TAB),
            InputKey.CapsLock => Scancode.From((short)Win32.WindowsScanCode.CAPITAL),
            InputKey.Numlock => Scancode.From((short)Win32.WindowsScanCode.NUMLOCK),
            InputKey.Delete => Scancode.From((short)Win32.WindowsScanCode.DELETE),
            InputKey.Backspace => Scancode.From((short)Win32.WindowsScanCode.BACK),
            InputKey.Num0 => Scancode.From((short)Win32.WindowsScanCode.NUMPAD0),
            InputKey.Num1 => Scancode.From((short)Win32.WindowsScanCode.NUMPAD1),
            InputKey.Num2 => Scancode.From((short)Win32.WindowsScanCode.NUMPAD2),
            InputKey.Num3 => Scancode.From((short)Win32.WindowsScanCode.NUMPAD3),
            InputKey.Num4 => Scancode.From((short)Win32.WindowsScanCode.NUMPAD4),
            InputKey.Num5 => Scancode.From((short)Win32.WindowsScanCode.NUMPAD5),
            InputKey.Num6 => Scancode.From((short)Win32.WindowsScanCode.NUMPAD6),
            InputKey.Num7 => Scancode.From((short)Win32.WindowsScanCode.NUMPAD7),
            InputKey.Num8 => Scancode.From((short)Win32.WindowsScanCode.NUMPAD8),
            InputKey.Num9 => Scancode.From((short)Win32.WindowsScanCode.NUMPAD9),
            InputKey.LeftArrow => Scancode.From((short)Win32.WindowsScanCode.LEFT),
            InputKey.RightArrow => Scancode.From((short)Win32.WindowsScanCode.RIGHT),
            InputKey.UpArrow => Scancode.From((short)Win32.WindowsScanCode.UP),
            InputKey.DownArrow => Scancode.From((short)Win32.WindowsScanCode.DOWN),
            _ => throw new ArgumentOutOfRangeException(
                $"{key} does not have a valid scancode equivalent on Windows.")
        };
    }

    public static Win32.WindowsVirtualKey ToWindowsVirtual(InputKey key)
    {
        // https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
        
        return key switch
        {
            InputKey.F1 => Win32.WindowsVirtualKey.F1,
            InputKey.F2 => Win32.WindowsVirtualKey.F2,
            InputKey.F3 => Win32.WindowsVirtualKey.F3,
            InputKey.F4 => Win32.WindowsVirtualKey.F4,
            InputKey.F5 => Win32.WindowsVirtualKey.F5,
            InputKey.F6 => Win32.WindowsVirtualKey.F6,
            InputKey.F7 => Win32.WindowsVirtualKey.F7,
            InputKey.F8 => Win32.WindowsVirtualKey.F8,
            InputKey.F9 => Win32.WindowsVirtualKey.F9,
            InputKey.F10 => Win32.WindowsVirtualKey.F10,
            InputKey.F11 => Win32.WindowsVirtualKey.F11,
            InputKey.F12 => Win32.WindowsVirtualKey.F12,
            InputKey.F13 => Win32.WindowsVirtualKey.F13,
            InputKey.F14 => Win32.WindowsVirtualKey.F14,
            InputKey.F15 => Win32.WindowsVirtualKey.F15,
            InputKey.F16 => Win32.WindowsVirtualKey.F16,
            InputKey.F17 => Win32.WindowsVirtualKey.F17,
            InputKey.F18 => Win32.WindowsVirtualKey.F18,
            InputKey.F19 => Win32.WindowsVirtualKey.F19,
            InputKey.F20 => Win32.WindowsVirtualKey.F20,
            InputKey.F21 => Win32.WindowsVirtualKey.F21,
            InputKey.F22 => Win32.WindowsVirtualKey.F22,
            InputKey.F23 => Win32.WindowsVirtualKey.F23,
            InputKey.F24 => Win32.WindowsVirtualKey.F24,
            InputKey.VolumeMute => Win32.WindowsVirtualKey.VOLUME_MUTE,
            InputKey.VolumeDown => Win32.WindowsVirtualKey.VOLUME_UP,
            InputKey.VolumeUp => Win32.WindowsVirtualKey.VOLUME_DOWN,
            InputKey.PlaybackPrevious => Win32.WindowsVirtualKey.MEDIA_PREV_TRACK,
            InputKey.PlaybackPlayPause => Win32.WindowsVirtualKey.MEDIA_PLAY_PAUSE,
            InputKey.PlaybackNext => Win32.WindowsVirtualKey.MEDIA_NEXT_TRACK,
            InputKey.Zero => Win32.WindowsVirtualKey.KEY_0,
            InputKey.One => Win32.WindowsVirtualKey.KEY_1,
            InputKey.Two => Win32.WindowsVirtualKey.KEY_2,
            InputKey.Three => Win32.WindowsVirtualKey.KEY_3,
            InputKey.Four => Win32.WindowsVirtualKey.KEY_4,
            InputKey.Five => Win32.WindowsVirtualKey.KEY_5,
            InputKey.Six => Win32.WindowsVirtualKey.KEY_6,
            InputKey.Seven => Win32.WindowsVirtualKey.KEY_7,
            InputKey.Eight => Win32.WindowsVirtualKey.KEY_8,
            InputKey.Nine => Win32.WindowsVirtualKey.KEY_9,
            InputKey.A => Win32.WindowsVirtualKey.KEY_A,
            InputKey.B => Win32.WindowsVirtualKey.KEY_B,
            InputKey.C => Win32.WindowsVirtualKey.KEY_C,
            InputKey.D => Win32.WindowsVirtualKey.KEY_D,
            InputKey.E => Win32.WindowsVirtualKey.KEY_E,
            InputKey.F => Win32.WindowsVirtualKey.KEY_F,
            InputKey.G => Win32.WindowsVirtualKey.KEY_G,
            InputKey.H => Win32.WindowsVirtualKey.KEY_H,
            InputKey.I => Win32.WindowsVirtualKey.KEY_I,
            InputKey.J => Win32.WindowsVirtualKey.KEY_J,
            InputKey.K => Win32.WindowsVirtualKey.KEY_K,
            InputKey.L => Win32.WindowsVirtualKey.KEY_L,
            InputKey.M => Win32.WindowsVirtualKey.KEY_M,
            InputKey.N => Win32.WindowsVirtualKey.KEY_N,
            InputKey.O => Win32.WindowsVirtualKey.KEY_O,
            InputKey.P => Win32.WindowsVirtualKey.KEY_P,
            InputKey.Q => Win32.WindowsVirtualKey.KEY_Q,
            InputKey.R => Win32.WindowsVirtualKey.KEY_R,
            InputKey.S => Win32.WindowsVirtualKey.KEY_S,
            InputKey.T => Win32.WindowsVirtualKey.KEY_T,
            InputKey.U => Win32.WindowsVirtualKey.KEY_U,
            InputKey.V => Win32.WindowsVirtualKey.KEY_V,
            InputKey.W => Win32.WindowsVirtualKey.KEY_W,
            InputKey.X => Win32.WindowsVirtualKey.KEY_X,
            InputKey.Y => Win32.WindowsVirtualKey.KEY_Y,
            InputKey.Z => Win32.WindowsVirtualKey.KEY_Z,
            InputKey.Shift => Win32.WindowsVirtualKey.SHIFT,
            InputKey.LeftShift => Win32.WindowsVirtualKey.LSHIFT,
            InputKey.RightShift => Win32.WindowsVirtualKey.RSHIFT,
            InputKey.Alt => Win32.WindowsVirtualKey.MENU,
            InputKey.LeftAlt => Win32.WindowsVirtualKey.LMENU,
            InputKey.RightAlt => Win32.WindowsVirtualKey.RMENU,
            InputKey.Control => Win32.WindowsVirtualKey.CONTROL,
            InputKey.LeftControl => Win32.WindowsVirtualKey.LCONTROL,
            InputKey.RightControl => Win32.WindowsVirtualKey.RCONTROL,
            InputKey.Backtick => Win32.WindowsVirtualKey.OEM_3,
            InputKey.Tilde => Win32.WindowsVirtualKey.OEM_3,
            InputKey.ExclamationPoint => Win32.WindowsVirtualKey.KEY_1,
            InputKey.At => Win32.WindowsVirtualKey.KEY_2,
            InputKey.Hashtag => Win32.WindowsVirtualKey.KEY_3,
            InputKey.Dollar => Win32.WindowsVirtualKey.KEY_4,
            InputKey.Percent => Win32.WindowsVirtualKey.KEY_5,
            InputKey.Caret => Win32.WindowsVirtualKey.KEY_6,
            InputKey.Ampersand => Win32.WindowsVirtualKey.KEY_7,
            InputKey.Star => Win32.WindowsVirtualKey.MULTIPLY,
            InputKey.LeftParenthesis => Win32.WindowsVirtualKey.KEY_9,
            InputKey.RightParenthesis => Win32.WindowsVirtualKey.KEY_0,
            InputKey.Dash => Win32.WindowsVirtualKey.SUBTRACT,
            InputKey.Underscore => Win32.WindowsVirtualKey.OEM_MINUS,
            InputKey.Equals => Win32.WindowsVirtualKey.OEM_PLUS,
            InputKey.Plus => Win32.WindowsVirtualKey.ADD,
            InputKey.LeftBracket => Win32.WindowsVirtualKey.OEM_4,
            InputKey.LeftCurlyBracket => (Win32.WindowsVirtualKey)123, //Win32.WindowsVirtualKey.OEM_4,
            InputKey.RightBracket => Win32.WindowsVirtualKey.OEM_6,
            InputKey.RightCurlyBracket => Win32.WindowsVirtualKey.OEM_6,
            InputKey.VerticalBar => Win32.WindowsVirtualKey.OEM_5,
            InputKey.Backslash => Win32.WindowsVirtualKey.OEM_5,
            InputKey.Semicolon => Win32.WindowsVirtualKey.OEM_1,
            InputKey.Colon => Win32.WindowsVirtualKey.OEM_1,
            InputKey.SingleQuote => Win32.WindowsVirtualKey.OEM_7,
            InputKey.DoubleQuote => Win32.WindowsVirtualKey.OEM_7,
            InputKey.Comma => Win32.WindowsVirtualKey.OEM_COMMA,
            InputKey.LessThan => Win32.WindowsVirtualKey.OEM_COMMA,
            InputKey.Period => Win32.WindowsVirtualKey.OEM_PERIOD,
            InputKey.GreaterThan => Win32.WindowsVirtualKey.OEM_PERIOD,
            InputKey.Slash => Win32.WindowsVirtualKey.DIVIDE,
            InputKey.QuestionMark => Win32.WindowsVirtualKey.OEM_2,
            InputKey.Enter => Win32.WindowsVirtualKey.RETURN,
            InputKey.Tab => Win32.WindowsVirtualKey.TAB,
            InputKey.CapsLock => Win32.WindowsVirtualKey.CAPITAL,
            InputKey.Numlock => Win32.WindowsVirtualKey.NUMLOCK,
            InputKey.Escape => Win32.WindowsVirtualKey.ESCAPE,
            InputKey.Delete => Win32.WindowsVirtualKey.DELETE,
            InputKey.Backspace => Win32.WindowsVirtualKey.BACK,
            InputKey.Num0 => Win32.WindowsVirtualKey.NUMPAD0,
            InputKey.Num1 => Win32.WindowsVirtualKey.NUMPAD1,
            InputKey.Num2 => Win32.WindowsVirtualKey.NUMPAD2,
            InputKey.Num3 => Win32.WindowsVirtualKey.NUMPAD3,
            InputKey.Num4 => Win32.WindowsVirtualKey.NUMPAD4,
            InputKey.Num5 => Win32.WindowsVirtualKey.NUMPAD5,
            InputKey.Num6 => Win32.WindowsVirtualKey.NUMPAD6,
            InputKey.Num7 => Win32.WindowsVirtualKey.NUMPAD7,
            InputKey.Num8 => Win32.WindowsVirtualKey.NUMPAD8,
            InputKey.Num9 => Win32.WindowsVirtualKey.NUMPAD9,
            InputKey.LeftArrow => Win32.WindowsVirtualKey.LEFT,
            InputKey.RightArrow => Win32.WindowsVirtualKey.RIGHT,
            InputKey.UpArrow => Win32.WindowsVirtualKey.UP,
            InputKey.DownArrow => Win32.WindowsVirtualKey.DOWN,
            _ => throw new ArgumentOutOfRangeException(
                $"{key} does not have a valid virtual key equivalent on Windows.")
        };
    }
    
    #endregion
}